---
- name: Install Android Studio dependencies
  become: true
  apt:
      name:
      - libc6:i386
      - libncurses5:i386
      - libstdc++6:i386
      - lib32z1
      - libbz2-1.0:i386

- name: Install Android Studio
  become: true
  unarchive:
      creates: /opt/android-studio
      dest: /opt/
      remote_src: yes
      src: https://redirector.gvt1.com/edgedl/android/studio/ide-zips/4.0.1.0/android-studio-ide-193.6626763-linux.tar.gz

- name: Have Android Studio desktop icon
  copy:
      src: Android Studio.desktop
      dest: "{{ansible_user_dir}}/Desktop"
      mode: 0775

- name: Android SDK tools in PATH
  template:
      src: 01-android.conf
      dest: "{{ user_bashrcd }}/"
